### PR TITLE
Bump node forge version

### PR DESCRIPTION
**Pull request by stein321**

### CODE REVIEW

**Comment by WilliamRADFunk** [comment]
Any chance we can up the priority on this PR getting in? win-ca is the only dependency we have left that still uses the vulnerable version of node-forge.

**Comment by stein321** [comment]
@WilliamRADFunk I'm rerunning the tests - hopefully they failed due to flakiness or app version

**Comment by jamesmontalvo3** [comment]
Any progress on this? Looks like the tests failed again, and both test runs [1] [2] failed only on Node 12 and 14 (not 6-11 or 13).

[1] https://ci.appveyor.com/project/ukoloff/win-ca/builds/42337049
[2] https://ci.appveyor.com/project/ukoloff/win-ca/builds/42431181

**Comment by ukoloff** [comment]
Hello, everybody!

Sorry for delay, but I have tough time now. I hope I will be free in a week and will tackle the problem. So far I see the only problem with test certificate CN mismatch, this is hopefuly easily tackled.

**Comment by ukoloff** [comment]
node-forge version bumped, win-ca v3.5.0 is published.

PR was rejected for sake of clarity ;-)

**Comment by stein321** [comment]
thanks for taking care of it @ukoloff !

**Pull request closed without merging**
