### PR TITLE
Make N-API addon threadsafe

### PR DESCRIPTION
**Pull request by addaleax**
There’s no need to rely on global, static data here. N-API provides
a way to pass data to functions without storing them externally
(which is less pretty, but, well, it avoids the memory leak from
`SuppressDestruct()` and makes the whole addon threadsafe).

This also adds a destructor for `Crypt32` that cleans up if the
class instance is still alive at Node.js instance shutdown
(e.g. when a Worker thread terminates).

### CODE REVIEW

**Comment by ukoloff** [comment]
Well, it seems to me, you understands the guts of N-API much better than me, so I'm inclined to accept your PR.

But I don't quite got the point: Crypt32::constructor is created once, never changed, never destroyed. What must happen for leak to occur?

> This also adds a destructor for `Crypt32`

Oh, this sounds reasonable.

**Comment by addaleax** [comment]
> But I don't quite got the point: Crypt32::constructor is created once, never changed, never destroyed. What must happen for leak to occur?

Oh, the leak is just that it outlives the Node.js instance (and with it, the JS object to which it refers) – for example, in an embedded application like Electron, you could have multiple Node.js instances in the same process. It’s not a big deal, it’s only one object – the more important bit is that moving away from a `static`/global variable makes the addon threadsafe. :)

**Comment by ukoloff** [comment]
Ok, you convinced me. 

Sorry for delay!

**Comment by ukoloff** [comment]
Interestingly, all tests pass in CI, but errors occur while running tests locally on Windows 7.

This may be issue of Node.js itself though. I'm going to investigate.

**Pull request merged**
