### PR TITLE
fix for bundler complaining about return outside of function

### PR DESCRIPTION
**Pull request by jgarces-tw**
Hi, while using browserify to bundle the module it complains that the return inside the first if on index.js is outside a function

instead of a return, could the other code be moved inside an else? cheers!

### CODE REVIEW

**Comment by ukoloff** [comment]
Yes, this can be easily fixed, but what's the point in doing it?

`win-ca` works only inside Node.js. It is **sure** to fail in browser.

What is your usage scenario? I can't understand.

**Comment by xaviergonz** [comment]
It is when bundling the node main process for an electron app in a single file so it is faster to load. Most electron apps do this, even the starter kits. 

Electron is separated into two worlds, the main process, which runs as a node app, and the renders, which run as a chromium instance.

**Comment by ukoloff** [comment]
Well, it can make sense. Okay.

But in this case you must also extract `root.exe` and put it next to the bundle.

**Comment by ukoloff** [comment]
v2.4.1 is out. Test, please.

**Pull request merged**
